### ISSUE TITLE
Different items / Same coordinates

### ISSUE THREAD

**Issue by symac** [omeka/plugin-Geolocation#30]
Hello,
when adding the same coordinates to different items, only one pin appears, which seems normal, but the popup makes the user think only one item is available at this place, would be nice to get some information in the tooltip giving access to all items related to the specific place.

**Comment by zerocrates** [comment]
This should be resolved in Geolocation 3.0 if you enable marker clustering (it will "spiderfy" clusters that are in exactly the same spot or otherwise too close to distinguish even at max zoom).
