### ISSUE TITLE
Geolocation Google map issue on Mac Chrome

### ISSUE THREAD

**Issue by ksclarke** [omeka/plugin-Geolocation#38]
When using the map on the contribution form, there seems to be an issue with the Javascript on Mac Chrome. Chrome on other platforms (Linux, for instance) does not have the problem. This was working at one point, we believe, so wonder if something changed on Google's end. The problem:

One goes to the Contribution form and gets presented with a dropdown to select a type of contribution, when the the type of contribution that's selected has a map on it. The loading of that type's form (after selecting the type in the dropdown) fails because of a Javascript exception: Uncaught ReferenceError: google is not defined

This seems to be the issue here: https://stackoverflow.com/questions/14229695/google-maps-api-throws-uncaught-referenceerror-google-is-not-defined-only-whe

The contribution form is loading the specific type's additional form data via AJAX but it's failing on Mac's Chrome. Not sure why it doesn't affect Linux's Chrome. Any ideas on a workaround?

**Comment by zerocrates** [comment]
Is that the only console error, or is there anything else, like something failing to load? Geolocation should be loading the Maps API on every page, so `google` should be defined.

It'd be pretty odd to have a difference like this between Chrome on Mac and other platforms so I suspect something else is going on.

**Comment by ksclarke** [comment]
Yes, it is odd that it would only be one Chrome. Safari on Mac works, fwiw. When the Javascript error happens, the item specific form stuff that should be loaded from the AJAX doesn't load so the page is just stuck at the drop down. There is no problem with loading the map on the other pages just the contribution dropdown page.

**Comment by zerocrates** [comment]
Do you have an accessible URL that shows the problem?

**Comment by ksclarke** [comment]
You can create a guest user account at http://echode.org/ and try it out (the site isn't live so can be uploaded to, tested with, etc.) It's only on the Mac/Chrome combo as far as I know. I don't see the problem myself (don't have a Mac to test with).

**Comment by kimisgold** [comment]
I just tested this with Chrome 51.0.2704.103 on 10.11.5 and had trouble replicating this; both the Story and Photo forms loaded as expected, map and everything. Photo form submitted successfully.

**Comment by ksclarke** [comment]
Hmm, okay, thanks @kimisgold. The reporter did say he did the standard things like clear the cache, hard refresh, etc. Puzzled.

**Comment by ksclarke** [comment]
@zerocrates I see you created an account too. Were you also not able to replicate the issue?

**Comment by ksclarke** [comment]
Oh, and it seems it's not just the contribution dropdown. He doesn't see the map anywhere on the site when using Chrome on the Mac (though Safari on Mac is okay). I've confirmed he has all extensions disabled.

**Comment by zerocrates** [comment]
I created an account to look, but I'm not currently on a Mac so I'm not really evidence one way or the other.

**Comment by zerocrates** [comment]
My own "site" has an [extremely sparse](http://zerocrates.org/omeka/items/map) Geolocation setup if you want just anything.

**Comment by ksclarke** [comment]
Just to update, the user reports that his Mac/Chrome also cannot display the map on your site, @zerocrates. Thanks for providing it for testing of this issue.

**Comment by zerocrates** [comment]
Interesting data point. That being said, there's not a whole lot we can do at the moment if we can't reproduce the issue outside that particular machine.

**Comment by ksclarke** [comment]
Yes, understood. I'll probably go to the local university this weekend and try their Macs to see if I can reproduce.

**Comment by mebrett** [comment]
I'm using Chrome Version 51.0.2704.103 (64-bit) on a Mac running OS X 10.11.5 and I just contributed a picture of the Mill at West Point on the Eno. Had no problem with the Geolocation aspect. Fwiw.

**Comment by ksclarke** [comment]
Thanks @mebrett for another data point.

**Comment by ksclarke** [comment]
Closing this as unreproducible. I've been unable to confirm it either on Macs I've tested with.

**Comment by deskstar** [comment]
I face the same problem, but it only happens in MacOS Sierra (10.12)
You can replicated the problem by using chrome in any machine running mac OS 10.12 with the following page
https://www.tutorialspoint.com/html5/geolocation_getcurrentposition.htm

While safari able to retrieve the location, chrome fail (all plugin disabled and js enabled)
