### ISSUE TITLE
Map display errors on admin-item-edit

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Geolocation#40]
[Reported on the forum initially](https://forum.omeka.org/t/geolocation-map-overlays-the-address-search-field-on-item-edit-form/1678) 

When I use Chrome (trying the branches of the core and the plugin mentioned, as well as master for both), I have the same problem as the initial report: map I can click into but no search field.
![chome-geolocation](https://cloud.githubusercontent.com/assets/2314070/18757710/1aef1dc0-80c3-11e6-8f92-748592f20674.png) 

Same issue in Firefox.

On Safari I only get the search options, no map.

**Comment by zerocrates** [comment]
JS console errors?

**Comment by zerocrates** [comment]
It's some sort of floating/clearing problem: the input is there, it's just drawing underneath the map.

**Comment by zerocrates** [comment]
Not really sure why it's appearing now though, and not before.

**Comment by mebrett** [comment]
That's what so confusing.

**Comment by zerocrates** [comment]
Fixed by aa112422ddf56b696c949de85764f31fa0e5dcbf
