### ISSUE TITLE
Test Geolocation 2.2.5

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-Geolocation#41]
Latest master.

Just a sanity/regression check pretty much.

The only major "interesting" area would be the Contribution integration: some stuff about how that works has changed, so let's just double-confirm that it's working correctly still.

**Comment by mebrett** [comment]
The Map is showing up on the Contribution form when "Add Map to Contribution Form" is ticked. But the geolocation data isn't sticking to the item - when I go to review the items on admin (as superuser), there's no location data assigned to them. On branch master of Contribution.

**Comment by zerocrates** [comment]
Well that would definitely be a problem. Is it working in 2.2.4?

**Comment by mebrett** [comment]
Yes - on 2.2.4 the location sticks.

**Comment by zerocrates** [comment]
Okay try latest master again

**Comment by mebrett** [comment]
Location is sticky again!
