### ISSUE TITLE
Update documentation for API key

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Geolocation#45]
Latest Geolocation has a first configuration option for the Google API key, but that's not reflected in the [documentation](http://omeka.org/codex/Plugins/Geolocation_2.0) screenshot or explanation. They should just click the 'Get A Key' button from the page we link to on the configuration page.

**Comment by mebrett** [comment]
I'm going to assume the "get a key" button only shows up if people haven't already entered an API key?
