### ISSUE TITLE
Maps not loading on item page?

### ISSUE THREAD

**Issue by emeehangsu** [omeka/plugin-Geolocation#46]
I have installed Geolocation 2.2.5 on Omeka 2.5 and am running into a problem where the 'maps' tab on items does not work.  The page seems to incompletely load the map applet, and the address search box does not work.  Neither am I able to manipulate the map.

The 'map' tab on Omeka loads the applet correctly and I am able to zoom, change from satellite to terrain, etc.

**Comment by patrickmj** [comment]
I'm not entirely sure if the error I'm seeing is the same as yours, but if so there's a good chance that you need to get an API key from Google and add it to the plugin configuration. There's a link to the page to do that on the plugin configuration page.

**Comment by emeehangsu** [comment]
Yea, I've got an API key, and after messing around with  it a bit it seems that the problem is in fact intermittent.  The map applet just doesn't load all the way every time.
