### ISSUE TITLE
Lat/Long point defaults to nearest street/road

### ISSUE THREAD

**Issue by jcmundy** [omeka/plugin-Geolocation#47]
Is that the expected behavior, or do I have a setting wrong?  
We are inputting GPS points that should be between streets, but when it "finds" the location it puts the point on the nearest street.  When we search in Google Maps itself it takes us to the exact point.  Can I change a setting to have the GPS points go to the exact location, or is that a feature you could incorporate at some point?  Thanks.

**Comment by zerocrates** [comment]
Can you give an example of a lat/long where the deviation is clear?

**Comment by jcmundy** [comment]
Our points are within a cemetery, so for instance 33.748662, -84.370454  shows up between the streets on Google Maps, but on a street in the plugin.

**Comment by zerocrates** [comment]
I'll take a look. We pretty much just pass everything to the Google Maps geocoder, and it's mostly seemed like it's done the right thing but it's very believable that it would snap to addresses or streets. The simplest answer would probably be to just detect something that looks like lat/lon and skip the geocoder altogether.

**Comment by jcmundy** [comment]
It looks like the input form is specifically using the $address; element.  Is there somewhere else that I can input the point by lat/long?  Thank you again for your help.

**Comment by zerocrates** [comment]
The plugin itself doesn't provide any method of input besides clicking and the address input.

What I've just gone ahead and done is add a little code to detect "addresses" that look like lat/long pairs and just use them directly without geocoding; this should stop them from getting snapped to roads.

**Comment by jcmundy** [comment]
Thanks!  That appears to be working for me!
