### ISSUE TITLE
Test lat/long address input change

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-Geolocation#48]
Master branch of the plugin.

The change being tested is in the map input tab on item add/edit: it now accepts latitude-longitude pairs directly in the address field(as two decimal numbers separated by a comma or semicolon). The prior code accepted them, but would snap them to the nearest road, so try to pick points not on a road when testing.

This only affects input into the address box, not manual clicking to pick points.

Also confirm "normal" addresses still work as expected.

**Comment by mebrett** [comment]
Street addresses still work, and lat/long works as well - does not try to redirect to the closest street.
