### ISSUE TITLE
How do you use search form to find items without geolocation coordinates?

### ISSUE THREAD

**Issue by akprtll** [omeka/plugin-Geolocation#52]
The Omeka search form seems to allow you to seek items that are within a certain distance of a location, but is there syntax that can be used in the search form to find items that have not been geolocated? (The goal is to make a list for manually adding the geolocation information.)

**Comment by zerocrates** [comment]
The plugin doesn't include an option to search for un-located items.

The data for doing that is all there, there just needs to be added a query parameter that tells us to do it: the opposite of the existing `only_map_items`.

**Comment by zerocrates** [comment]
Geolocation 3.1 includes this feature.
